defaults: &defaults
  cookie_domain: <%= ENV['APP_HOST'] || 'localhost' %>
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'localhost' %>

staging:
  <<: *defaults
  default_url_options: 
    host: tasky.brandymint.ru

production:
  <<: *defaults
  default_url_options: 
    host: tasky.online

development:
  <<: *defaults

test:
  <<: *defaults

  # test.host
